apiVersion: v1
kind: Secret
metadata:
  name: git-credentials
  namespace: airflow
data:
  GITSYNC_USERNAME: echo -n "user-name" | base64
  GITSYNC_PASSWORD: echo -n "access-token" | base64
  GIT_SYNC_USERNAME: echo -n "user-name" | base64
  GIT_SYNC_PASSWORD: echo -n "access-token" | base64
